import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {DataTableProvider} from "@/components/data-table/tools/data-table-provider";
import {TooltipProvider} from "@/components/ui/tooltip";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TooltipProvider>
          <DataTableProvider>
            {children}
          </DataTableProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
